// Generated by CoffeeScript 1.6.2
var ccSvc, envir;

ccSvc = require('../lib/ccxmleventemitter');

envir = new ccSvc.CurrentCost128XMLBaseStation('/dev/ttyUSB0', {
  useOSTime: true,
  debug: false,
  emitBaseEvery: 30,
  reading: {
    '9': 1100.000
  }
});

envir.on('base', function(eventinfo) {
  return console.log("This base station is using " + eventinfo.src + " firmware and has been running for " + eventinfo.dsb + " days. The temperature is currently " + eventinfo.temp);
});

envir.on('sensor', function(eventinfo) {
  if (eventinfo.sensor === '0') {
    return console.log("Whole House consumption reported as  " + eventinfo.watts + " watts");
  }
});

envir.on('impulse', function(eventinfo) {
  return console.log("There have been " + eventinfo.value + " impulses on sensor " + eventinfo.sensor + " since the sensor was powered on");
});

envir.on('impulse-reading', function(eventinfo) {
  return console.log("Sensor " + eventinfo.sensor + " reports a reading of " + eventinfo.reading);
});

envir.on('impulse-delta', function(eventinfo) {
  return console.log("There have been " + eventinfo.delta + " impulses on sensor " + eventinfo.sensor + " since the last reported event");
});

envir.on('impulse-avg', function(eventinfo) {
  return console.log("Sensor " + eventinfo.sensor + " reports an average consumption of " + eventinfo.avg + " units since last reported event");
});

process.on('SIGINT', function() {
  console.log("\ngracefully shutting down from  SIGINT (Crtl-C)");
  envir.close();
  envir = null;
  console.log("--EXIT--");
  return process.exit(0);
});
